use crate::hlist::{Cons, Nil};
use core::marker::PhantomData;

/// Read access to resource `R`.
pub struct Read<R>(PhantomData<R>);

/// Write access to resource `R`.
pub struct Write<R>(PhantomData<R>);

/// Partitioned access to resource `R` at key `K`.
///
/// e.g. `Read<Part<Storage, T>>` reads only the `T` region of `Storage`.
pub struct Part<R, K>(PhantomData<(R, K)>);

/// Compile-time type identity via [`type_name`](core::any::type_name).
///
/// On nightly `type_name` is `const`, so [`KeyEq`] compares two resource types
/// for identity by comparing their (fully-qualified) type-name strings in a
/// `const` context — no per-type key registration, no hashing, no derive.
/// `type_name` already distinguishes generic instantiations (`Foo<A>` vs
/// `Foo<B>`), so nothing has to fold generics in by hand.
///
/// `type_name` is not *guaranteed* unique, but distinct types are distinct in
/// practice; a collision would over-report a conflict (a spurious error), never
/// miss one.

/// `const`-comparable byte-wise string equality.
const fn str_eq(a: &str, b: &str) -> bool {
    let (a, b) = (a.as_bytes(), b.as_bytes());
    if a.len() != b.len() {
        return false;
    }
    let mut i = 0;
    while i < a.len() {
        if a[i] != b[i] {
            return false;
        }
        i += 1;
    }
    true
}

/// Structural equality of two resource types: `EQ` is `true` iff `A` and `B` are
/// the same type, compared by [`type_name`](core::any::type_name).
pub trait KeyEq<Rhs> {
    const EQ: bool;
}

impl<A, B> KeyEq<B> for A {
    const EQ: bool = str_eq(core::any::type_name::<A>(), core::any::type_name::<B>());
}

/// Resource containment (paths).
///
/// Beyond bare identity, a resource may be *nested inside* another: e.g. a
/// `Config<T>` slot lives within `Storage`. Accessing the child therefore
/// overlaps any access to an ancestor, while two distinct children (a different
/// `T`) stay disjoint from each other.
///
/// Each resource exposes a [`HasPath::Path`] — the chain of resource types from
/// the root ancestor down to and including itself, as a [`PCons`]/[`PNil`] list.
/// Two resources *overlap* iff one path is a prefix of the other, decided by
/// [`PathOverlap`] comparing elements with [`KeyEq`].

/// The empty path.
pub struct PNil;
/// A path cell: ancestor key `H` followed by the rest of the path `T`.
pub struct PCons<H, T>(PhantomData<(H, T)>);

/// A resource-containment path (a [`PCons`]/[`PNil`] chain, root first) that can
/// be extended at its deepest end.
pub trait PathList {
    /// This path with key `K` appended as the new deepest element.
    type Push<K>: PathList;
}

impl PathList for PNil {
    type Push<K> = PCons<K, PNil>;
}

impl<H, T: PathList> PathList for PCons<H, T> {
    type Push<K> = PCons<H, T::Push<K>>;
}

/// Associates a resource with its containment [path](PathList), from the root
/// ancestor down to itself. Generated by `#[accesses]`; `Part` extends it.
pub trait HasPath {
    type Path: PathList;
}

/// A partition `Part<R, K>` sits one level below `R`: its path is `R`'s path
/// with the partition key appended, so it overlaps any whole-`R` access but is
/// disjoint from partitions with a different key.
impl<R, K> HasPath for Part<R, K>
where
    R: HasPath,
{
    type Path = <<R as HasPath>::Path as PathList>::Push<K>;
}

/// `VALUE` is `true` iff the two paths overlap — i.e. one is a prefix of the
/// other, so the resources are identical or one contains the other.
pub trait PathOverlap<Other> {
    const VALUE: bool;
}

// An empty path is a prefix of any path (and vice versa): they overlap.
impl PathOverlap<PNil> for PNil {
    const VALUE: bool = true;
}
impl<H, T> PathOverlap<PCons<H, T>> for PNil {
    const VALUE: bool = true;
}
impl<H, T> PathOverlap<PNil> for PCons<H, T> {
    const VALUE: bool = true;
}
// Two non-empty paths overlap iff their heads name the same resource and the
// remainders still overlap; diverging heads mean disjoint subtrees.
impl<H1, T1, H2, T2> PathOverlap<PCons<H2, T2>> for PCons<H1, T1>
where
    H1: KeyEq<H2>,
    T1: PathOverlap<T2>,
{
    const VALUE: bool = <H1 as KeyEq<H2>>::EQ && <T1 as PathOverlap<T2>>::VALUE;
}

/// Pairwise conflict rule: two accesses conflict iff their resources *overlap*
/// (are equal, or one contains the other — see [`PathOverlap`]) and at least one
/// is a `Write`.
pub trait ConflictsWith<T> {
    const VALUE: bool;
}

/// `Read` vs `Read` => two shared reads, never conflict.
impl<A, B> ConflictsWith<Read<B>> for Read<A> {
    const VALUE: bool = false;
}

/// `Read<A>` vs `Write<B>` => conflict iff `A` and `B` overlap.
impl<A, B> ConflictsWith<Write<B>> for Read<A>
where
    A: HasPath,
    B: HasPath,
    <A as HasPath>::Path: PathOverlap<<B as HasPath>::Path>,
{
    const VALUE: bool = <<A as HasPath>::Path as PathOverlap<<B as HasPath>::Path>>::VALUE;
}

/// `Write<A>` vs `Read<B>` => conflict iff `A` and `B` overlap.
impl<A, B> ConflictsWith<Read<B>> for Write<A>
where
    A: HasPath,
    B: HasPath,
    <A as HasPath>::Path: PathOverlap<<B as HasPath>::Path>,
{
    const VALUE: bool = <<A as HasPath>::Path as PathOverlap<<B as HasPath>::Path>>::VALUE;
}

/// `Write<A>` vs `Write<B>` => two writes, conflict iff `A` and `B` overlap.
impl<A, B> ConflictsWith<Write<B>> for Write<A>
where
    A: HasPath,
    B: HasPath,
    <A as HasPath>::Path: PathOverlap<<B as HasPath>::Path>,
{
    const VALUE: bool = <<A as HasPath>::Path as PathOverlap<<B as HasPath>::Path>>::VALUE;
}

/// `VALUE` is `true` iff access `H` conflicts with any element of the list.
pub trait AnyConflict<H> {
    const VALUE: bool;
}

/// Nothing to conflict with in an empty list.
impl<H> AnyConflict<H> for Nil {
    const VALUE: bool = false;
}

/// `H` conflicts with the list if it conflicts with the head or with any element
/// of the tail.
impl<H, TH, TT> AnyConflict<H> for Cons<TH, TT>
where
    TH: ConflictsWith<H>,
    TT: AnyConflict<H>,
{
    const VALUE: bool = <TH as ConflictsWith<H>>::VALUE || <TT as AnyConflict<H>>::VALUE;
}

/// `VALUE` is `true` iff the whole access list is internally conflict-free.
pub trait NoConflicts {
    const VALUE: bool;
}

/// An empty list is trivially conflict-free.
impl NoConflicts for Nil {
    const VALUE: bool = true;
}

/// A list is conflict-free iff its head clashes with nothing in the tail and the
/// tail is itself conflict-free.
impl<H, T> NoConflicts for Cons<H, T>
where
    T: NoConflicts + AnyConflict<H>,
{
    const VALUE: bool = !<T as AnyConflict<H>>::VALUE && <T as NoConflicts>::VALUE;
}
